version: '3'
services: 
  ipython:
    image: dogosousa/ipython
    container_name: ipython
    ports: 
      - "8888:8888"
    volumes: 
      #- ${HOME}/PROCESSADA:/opt/work/PROCESSADA
      - /mnt/geo/COTIC/GEOPROCESSAMENTO/GEO_DADOS/2_RASTER/2.1_ORTO/PROCESSAR_SENTINEL/:/opt/work